package com.nuc.gzq.autoscript.Data;

public class Constants {
    public Constants(){}

    public final String InterfacePrefix = "XCOS_";
    public final String Comment_1 = "//========================================================\n";
    public final String Comment_2 = "//functionname : \n";
    public final String Comment_3 = "//Author       : \n";
    public final String Comment_4 = "//CreateTime   : \n";
    public final String Comment_5 = "//This function is automatically generated by the program.\n";
    public final String Infacecontent1 = "function [x,y,typ] = (job,arg1,arg2)\n";
    public final String Infacecontent2 = "\tx = [];\n" +
            "\ty = [];\n" +
            "\ttyp = [];\n" +
            "\tselect job\n" +
            "\tcase \"set\" then\n" +
            "\t\tx = arg1;\n" +
            "\t\tgraphics = arg1.graphics;\n" +
            "\t\texprs = graphics.exprs;\n" +
            "\t\tmodel = arg1.model;\n";
    public final String Infacecontent3 = "\t\twhile %t do\n" +
            "\t\t\t[ok, constant, exprs] = scicos_getvalue(\"title\", [\"Constant\"], list(\"vec\",1), exprs);\n" +
            "\t\t\tif ~ok then\n" +
            "\t\t\t\tbreak;\n" +
            "\t\t\tend\n" +
            "\t\t\tif ~ok then\n" +
            "\t\t\t\tmess = \" WARING MESSAGES ！\";\n" +
            "\t\t\t\tmessage(mess);\n" +
            "\t\t\telse\n" +
            "\t\t\t\t//参数保存，此处可利用ipar,rpar,opar保存一些输入变量或者需要保存的值\n" +
            "\t\t\t\tgraphics.exprs = exprs;\n" +
            "\t\t\t\tx.graphics = graphics;\n" +
            "\t\t\t\tx.model = model;\n" +
            "\t\t\t\tbreak;\n" +
            "\t\t\tend\n" +
            "\t\tend\n";
    public final String Infacecontent4 = "\tcase \"define\" then\n" +
            "\t\tmodel = scicos_model();\n";
    public final String Infacecontent5 = "\t\tmodel.sim = list('',5);\n";
    public final String Infacecontent6 = "\t\tmodel.in = [];\n";
    public final String Infacecontent7 = "\t\tmodel.in2 = [];\n";
    public final String Infacecontent8 = "\t\tmodel.intyp = [];\n";
    public final String Infacecontent9 = "\t\tmodel.out = [];\n";
    public final String Infacecontent10 = "\t\tmodel.out2 = [];\n";
    public final String Infacecontent11 = "\t\tmodel.outtyp = [];\n";
    public final String Infacecontent12 = "\t\tmodel.evtin = [];\n";
    public final String Infacecontent13 = "\t\tmodel.evtout = [];\n";
    public final String Infacecontent14 = "\t\tmodel.state = [];\n" +
            "\t\tmodel.opar = list();\n" +
            "\t\tmodel.ipar = [];\n" +
            "\t\tmodel.ipar = [];\n" +
            "\t\tmodel.dstate = [];\n";
    public final String Infacecontent15 = "\t\tmodel.blocktype = \"\";\n";
    public final String Infacecontent16 = "\t\tmodel.dep_ut = [];\n";
    public final String Infacecontent17 = "\t\texprs = [];\n" +
            "\t\tgr_i = [];\n" +
            "\t\tx = standard_define([4 2],model,exprs,gr_i);\n" +
            "\tend\n" +
            "endfunction\n";
    public final String CalculatePrefix = "SROS_";
    public final String Calculatecontent1 = "function block = (block,flag)\n" +
            "\tif flag == 4 then\n" +
            "\t\t//初始化状态\n" +
            "\t\t\n" +
            "\tend\n" +
            "\tif flag == 6 then\n" +
            "\t\t//重新初始化状态\n" +
            "\t\t\t\n" +
            "\tend\n" +
            "\tif flag == 0 then\n" +
            "\t\t//计算连续时间状态的导数\n" +
            "\t\t\n" +
            "\tend\t\n" +
            "\tif flag == 1 then\n" +
            "\t\t//计算模块输出\n" +
            "\t\t\n" +
            "\tend\n" +
            "\tif flag == 2 then\n" +
            "\t\t//更新外部激活引起的状态变化\n" +
            "\t\t\n" +
            "\tend\n" +
            "\tif flag == 3 then\n" +
            "\t\t//安排激活输出延迟时间\n" +
            "\t\t\n" +
            "\tend\n" +
            "\tif flag == 7 then\n" +
            "\t\t//用于隐式模块\n" +
            "\t\t\n" +
            "\tend\n" +
            "\tif flag == 9 then\n" +
            "\t\t//计算过零面和设置模式\n" +
            "\t\t\n" +
            "\tend\n" +
            "\tif flag == 5 then\n" +
            "\t\t//最后调用模块的结束状态\n" +
            "\t\t\n" +
            "\tend\n" +
            "endfunction\n";
}
