package com.nuc.gzq.autoscript.Data;

public class Constants {
    public Constants(){}

    public final String InterfacePrefix = "XCOS_";
    public final String Comment_1 = "//========================================================\n";
    public final String Comment_2 = "//functionname : \n";
    public final String Comment_3 = "//Author       : \n";
    public final String Comment_4 = "//Time         : \n";
    public final String Comment_5 = "//This function is automatically generated by the program.\n";
    public final String Infacecontent1 = "function [x,y,typ] = (job,arg1,arg2)\n";
    public final String Infacecontent2 = "\tx = [];\n" +
            "\ty = [];\n" +
            "\ttyp = [];\n" +
            "\tselect job\n" +
            "\tcase \"set\" then\n" +
            "\t\tx = arg1;\n" +
            "\t\tgraphics = arg1.graphics;\n" +
            "\t\texprs = graphics.exprs;\n" +
            "\t\tmodel = arg1.model;\n";
    public final String Infacecontent3 = "\t\twhile %t do\n" +
            "\t\t\t[ok, constant, exprs] = scicos_getvalue(\"title\", [\"Constant\"], list(\"vec\",1), exprs);\n" +
            "\t\t\tif ~ok then\n" +
            "\t\t\t\tbreak;\n" +
            "\t\t\tend\n" +
            "\t\t\tif ~ok then\n" +
            "\t\t\t\tmess = \" WARING MESSAGES ！\";\n" +
            "\t\t\t\tmessage(mess);\n" +
            "\t\t\telse\n";
    public final String Infacecontent4 = "\t\t\t\t//参数保存，此处可利用ipar,rpar,opar保存一些输入变量或者需要保存的值\n" +
            "\t\t\t\tgraphics.exprs = exprs;\n" +
            "\t\t\t\tx.graphics = graphics;\n" +
            "\t\t\t\tx.model = model;\n" +
            "\t\t\t\tbreak;\n";
    public final String Infacecontent5 = "\t\t\tend\n" +
            "\t\tend\n";
    public final String Infacecontent6 = "\tcase \"define\" then\n" +
            "\t\tmodel = scicos_model();\n" +
            "\t\tmodel.sim = list('SROS_fr_lvlhMat',5);\n" +
            "\t\tmodel.in = [];\n" +
            "\t\tmodel.in2 = [];\n" +
            "\t\tmodel.intyp = [];\n" +
            "\t\tmodel.out = [];\n" +
            "\t\tmodel.out2 = [];\n" +
            "\t\tmodel.outtyp = [];\n" +
            "\t\tmodel.evtin = [];\n" +
            "\t\tmodel.evtout = [];\n" +
            "\t\tmodel.state = [];\n" +
            "\t\tmodel.opar = list();\n" +
            "\t\tmodel.ipar = [];\n" +
            "\t\tmodel.ipar = [];\n" +
            "\t\tmodel.dstate = [];\n" +
            "\t\tmodel.blocktype = \"d\";\n" +
            "\t\tmodel.dep_ut = [%t %f];\n" +
            "\t\texprs = [];\n" +
            "\t\tgr_i = [];\n" +
            "\t\tx = standard_define([4 2],model,exprs,gr_i);\n" +
            "\tend\n" +
            "endfunction\n";
    public final String CalculatePrefix = "SROS_";
}
