package com.nuc.gzq.autoscript.Data;

public class Constants {
    public Constants(){}

    public final String InterfacePrefix = "XCOS_";
    public final String Comment_1 = "//========================================================\r\n";
    public final String Comment_2 = "//functionname : \r\n";
    public final String Comment_3 = "//Author       : \r\n";
    public final String Comment_4 = "//CreateTime   : \r\n";
    public final String Comment_5 = "//This function is automatically generated by the program.\r\n";
    public final String Infacecontent1 = "function [x,y,typ] = (job,arg1,arg2)\r\n";
    public final String Infacecontent2 = "\tx = [];\r\n" +
            "\ty = [];\r\n" +
            "\ttyp = [];\r\n" +
            "\tselect job\r\n" +
            "\tcase \"set\" then\r\n" +
            "\t\tx = arg1;\r\n" +
            "\t\tgraphics = arg1.graphics;\r\n" +
            "\t\texprs = graphics.exprs;\r\n" +
            "\t\tmodel = arg1.model;\r\n";
    public final String Infacecontent3 = "\t\twhile %t do\r\n" +
            "\t\t\t[ok, constant, exprs] = scicos_getvalue(\"title\", [\"Constant\"], list(\"vec\",1), exprs);\r\n" +
            "\t\t\tif ~ok then\r\n" +
            "\t\t\t\tbreak;\r\n" +
            "\t\t\tend\r\n" +
            "\t\t\tif ~ok then\r\n" +
            "\t\t\t\tmess = \" WARING MESSAGES ！\";\r\n" +
            "\t\t\t\tmessage(mess);\r\n" +
            "\t\t\telse\r\n" +
            "\t\t\t\t//Parameter save, here you can use ipar, rpar, opar to save some input variables or values that need to be saved\r\n" +
            "\t\t\t\tgraphics.exprs = exprs;\r\n" +
            "\t\t\t\tx.graphics = graphics;\r\n" +
            "\t\t\t\tx.model = model;\r\n" +
            "\t\t\t\tbreak;\r\n" +
            "\t\t\tend\r\n" +
            "\t\tend\r\n";
    public final String Infacecontent4 = "\tcase \"define\" then\r\n" +
            "\t\tmodel = scicos_model();\r\n";
    public final String Infacecontent5 = "\t\tmodel.sim = list('',5);\r\n";
    public final String Infacecontent6 = "\t\tmodel.in = [];\r\n";
    public final String Infacecontent7 = "\t\tmodel.in2 = [];\r\n";
    public final String Infacecontent8 = "\t\tmodel.intyp = [];\r\n";
    public final String Infacecontent9 = "\t\tmodel.out = [];\r\n";
    public final String Infacecontent10 = "\t\tmodel.out2 = [];\r\n";
    public final String Infacecontent11 = "\t\tmodel.outtyp = [];\r\n";
    public final String Infacecontent12 = "\t\tmodel.evtin = [];\r\n";
    public final String Infacecontent13 = "\t\tmodel.evtout = [];\r\n";
    public final String Infacecontent14 = "\t\tmodel.state = [];\r\n" +
            "\t\tmodel.opar = list();\r\n" +
            "\t\tmodel.ipar = [];\r\n" +
            "\t\tmodel.ipar = [];\r\n" +
            "\t\tmodel.dstate = [];\r\n";
    public final String Infacecontent15 = "\t\tmodel.blocktype = \"\";\r\n";
    public final String Infacecontent16 = "\t\tmodel.dep_ut = [];\r\n";
    public final String Infacecontent17 = "\t\texprs = [];\r\n" +
            "\t\tgr_i = [];\r\n" +
            "\t\tx = standard_define([4 2],model,exprs,gr_i);\r\n" +
            "\tend\r\n" +
            "endfunction\n";
    public final String CalculatePrefix = "SROS_";
    public final String Calculatecontent1 = "function block = (block,flag)\r\n" +
            "\tif flag == 4 then\r\n" +
            "\t\t//Initialization state\r\n" +
            "\t\t\r\n" +
            "\tend\r\n" +
            "\tif flag == 6 then\r\n" +
            "\t\t//Reinitialization state\r\n" +
            "\t\t\t\r\n" +
            "\tend\r\n" +
            "\tif flag == 0 then\r\n" +
            "\t\t//Calculate the derivative of the continuous time state\r\n" +
            "\t\t\r\n" +
            "\tend\t\r\n" +
            "\tif flag == 1 then\r\n" +
            "\t\t//Calculation module output\r\n" +
            "\t\t\r\n" +
            "\tend\r\n" +
            "\tif flag == 2 then\r\n" +
            "\t\t//Update state changes caused by external activation\r\n" +
            "\t\t\r\n" +
            "\tend\r\n" +
            "\tif flag == 3 then\r\n" +
            "\t\t//Schedule activation output delay time\r\n" +
            "\t\t\r\n" +
            "\tend\r\n" +
            "\tif flag == 7 then\r\n" +
            "\t\t//For implicit modules\r\n" +
            "\t\t\r\n" +
            "\tend\r\n" +
            "\tif flag == 9 then\r\n" +
            "\t\t//Calculate zero-crossing and setup mode\r\n" +
            "\t\t\r\n" +
            "\tend\r\n" +
            "\tif flag == 5 then\r\n" +
            "\t\t//Finally call the end state of the module\r\n" +
            "\t\t\r\n" +
            "\tend\r\n" +
            "endfunction\r\n";
}
